//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AperturaEncuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padron
    {
        public int IdPadron { get; set; }
        public string AlumnoNombre { get; set; }
        public int AlumnoDNI { get; set; }
        public string AlumnoMail { get; set; }
        public string AlumnoCel { get; set; }
        public string AlumnoHora { get; set; }
        public string AlumnoDia { get; set; }
        public int IdCapacitacion { get; set; }
        public int IdPlanCiudad { get; set; }
        public int AlumnoEdad { get; set; }
        public string AlumnoDomicilio { get; set; }
        public string AlumnoTel { get; set; }
        public string AlumnoBarrio { get; set; }
        public int IdEncuestaApertura { get; set; }
    }
}
