//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AperturaEncuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCiudad
    {
        public int IdPlanCiudad { get; set; }
        public int IdCiudad { get; set; }
        public int IdPlan { get; set; }
        public string MatriculaValor { get; set; }
        public int CuotaCantidad { get; set; }
        public string CuotaValor { get; set; }
        public string CuotaValorDescuento { get; set; }
        public string CertificadoValor { get; set; }
    }
}
