//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirmacionApertura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ciudad()
        {
            this.PlanCiudad = new HashSet<PlanCiudad>();
        }
    
        public int IdCiudad { get; set; }
        public string NombreCiudad { get; set; }
        public int HorasDuracion { get; set; }
        public int Jornadas { get; set; }
        public int FrecuenciaSemanal { get; set; }
        public string SalonDireccion { get; set; }
        public System.DateTime FechaInicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCiudad> PlanCiudad { get; set; }
    }
}
