//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirmacionApertura.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EncuestaApertura
    {
        public string True
        {
            get
            {
                return "true";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuestaApertura()
        {
            this.Padron = new HashSet<Padron>();
        }

        public int IdEncuestaApertura { get; set; }
        [Required(ErrorMessage = "Encuesta requerida")]
        [Range(1, 10)]
        public int EncuestaAsesoramiento { get; set; }
        public string EncuestaSugerencia { get; set; }

        public bool Finalizado { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Padron> Padron { get; set; }
    }
}
