//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirmacionApertura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCiudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanCiudad()
        {
            this.Padron = new HashSet<Padron>();
        }
    
        public int IdPlanCiudad { get; set; }
        public int IdCiudad { get; set; }
        public int IdPlan { get; set; }
        public string MatriculaValor { get; set; }
        public int CuotaCantidad { get; set; }
        public string CuotaValor { get; set; }
        public string CuotaValorDescuento { get; set; }
        public string CertificadoValor { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Padron> Padron { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
